---
# tasks file for kali

- name: Install Pure Ftpd
  apt:
    name: pure-ftpd 

- name: Install Mingw
  apt:
    name: mingw-w64

- name: Install Build Essential
  apt:
    name: build-essential

- name: Install GDB
  apt:
    name: gdb

- name: Install JDK
  apt:
    name: default-jdk

- name: Install Python-pip
  apt:
    name: python-pip

- name: Install MSSql Packages
  apt:
    name:
      - sqsh
      - freetds-bin
      - freetds-common
      - freetds-dev

- name: Install Gobuster
  apt:
    name: gobuster

- name: Install Seclists
  apt:
    name: seclists

- name: Install jxplorer
  apt:
    name: jxplorer

- name: Install bloodhound
  apt:
    name: bloodhound

- name: Install libssl-dev (pwntools dependency)
  apt:
    name: libssl-dev

- name: Install python3.8-dev
  apt:
    name: python3.8-dev

- name: Install pwntools
  pip:
    name: pwntools
    executable: pip

- name: Install ropper
  pip:
    name: ropper
    executable: pip

- name: Setup Vimrc
  template:
    src: .vimrc.j2
    dest: /root/.vimrc  

- name: Setup Vimrc
  template:
    src: .vimrc.j2
    dest: /home/kali/.vimrc  
    owner: kali
    group: kali

- name: Setup gnome terms
  template:
    src: open_gnometerms.desktop.j2
    dest: /usr/share/applications/open_gnometerms.desktop

- name: Copy gnome script
  copy:
    src: "{{gnome_script}}"
    dest: "{{gnome_loc}}/{{gnome_script}}" 
    mode: "0755"

- name: Create Pastables directory
  file:
    path: "{{pastables_dir}}"
    state: directory

- name: Get pastables
  git:
    repo: https://github.com/wshenk/pastables.git
    dest: "{{pastables_dir}}"

- name: Create Nullinux Directory
  file: 
    path: "{{nullinux_dir}}"
    state: directory

- name: Get Nullinux
  git:
    repo: https://github.com/m8r0wn/nullinux
    dest: "{{nullinux_dir}}"
  register: nullinux_install

- name: Install Nullinux
  shell: ./setup.sh
  args:
    chdir: "{{nullinux_dir}}"
  when: nullinux_install.changed

- name: Create pwndbg dir
  file:
    path: "{{pwndbg_dir}}"
    state: directory

- name: Get pwndbg
  git:
    repo: https://github.com/pwndbg/pwndbg.git
    dest: "{{pwndbg_dir}}"

- name: Ensure gdbinit exists
  file:
    path: /home/kali/.gdbinit
    state: touch
    owner: kali
    group: kali

- name: Check for pwndb install
  lineinfile:
    name: /home/kali/.gdbinit
    line: "source {{pwndbg_dir}}/gdbinit.py"
    state: present
  check_mode: present
  register: pwndbg_install    

- name: Install pwndbg
  shell: ./setup.sh
  args:
    chdir: "{{pwndbg_dir}}"
  when: pwndbg_install.changed
 
- name: Create directory for ghidra
  file:
    path: "{{ghidra_dir}}"
    state: directory

- name: Download Ghidra 
  get_url:
    url: "{{ghidra_url}}"
    dest: "{{ghidra_dir}}"

- name: Unzip Ghidra
  unarchive:
    src: "{{ghidra_dir}}/{{ghidra_file}}.{{ghidra_ext}}"
    dest: "{{ghidra_dir}}"

- name: Link Ghidra
  file:
    src: "{{ghidra_dir}}/{{ghidra_version}}/ghidraRun"
    dest: "/usr/local/bin/ghidraRun"
    state: link

- name: Setup Ghidra
  template:
    src: ghidra.desktop.j2
    dest: /usr/share/applications/ghidra.desktop

- name: Init msfdb
  shell: "msfdb init"
  args:
    chdir: "/home/kali/"
